apps/childs/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('create-chief-home',createChiefHomeView.as_view(), name = 'create_chief_home'),
    path('initial-diagnostic',initialDiagnosticView.as_view(), name = 'initial_diagnostic'),
    path('initial-diagnostic-embarazada',initialDiagnosticembarazadaView.as_view(), name = 'initial_diagnostic_embarazada'),
    path('care-dates',careDatesView.as_view(),name = 'care_dates'),
    path('list-monitoring',childMonitoringView.as_view(), name = 'list_monitoring'),
    path('list-childs',childListView.as_view(), name = 'list_childs'),
    path('list-person',personListView.as_view(), name = 'list_person'),
    path('list-chief',chiefListView.as_view(), name = 'list_chief'),
    path('create-person',personCreateView.as_view(), name = 'create_person'),
    path('create-person-familiar',personFamiliarCreateView.as_view(), name = 'create_person_familiar'),
    path('create-chief',chiefCreateView.as_view(), name = 'create_chief'),
    path('create-familiar',familiarCreateView.as_view(), name = 'create_familiar'),
]

caritas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from apps.homes.views import home_view
from apps.users.views import loginView,logoutUser

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('',login_required(home_view.as_view()), name = 'home'),
    path('accounts/login/',loginView.as_view(), name='login'),
    path('logout',logoutUser, name='logout'),
    path('homes/',include(('apps.homes.urls','homes'))),
    path('childs/',include(('apps.childs.urls','childs'))),
    path('church/',include(('apps.church.urls','church'))),
    path('supplies/',include(('apps.supplies.urls','supplies')))
]

apps/childs/models.py
from django.db import models
from apps.homes.models import home
from apps.church.models import church_group, church

class person(models.Model):
    """Model definition for persona."""

    MADUREZ = [('Niño', 'Niño'), ('Adulto','Adulto')]

    id_person = models.CharField(primary_key=True,max_length=30)
    dni = models.CharField('Cedula de persona', max_length=30, blank=True, null=False, unique=True)
    name_person = models.CharField('Nombre de la persona', max_length=50, blank=False, null=False)
    last_name_person = models.CharField('Apellido de la persona', max_length=50, blank=False, null=False)
    gener = models.CharField('Genero de la persona', max_length=10, blank=False, null=False)
    category = models.CharField('Madurez de la persona', max_length=10, blank=False, null=False, default='Niño', choices=MADUREZ)
    birth_date = models.DateField('Fecha de nacimiento de la persona', auto_now=False, auto_now_add=False)

    class Meta:
        """Meta definition for persona."""

        verbose_name = 'persona'
        verbose_name_plural = 'personas'

    def __str__(self):
        """Unicode representation of persona."""
        return '{0} {1}  C.I.:{2}'.format(self.name_person, self.last_name_person, self.dni)

class jefe_familiar(models.Model):
    """Model definition for jefe_familiar."""

    PROPIEDAD = [(None,'Selecione una opcion'),('Propietario','Propietario'), ('Alquilado','Alquilado'), ('Invasión','Invasión')]

    chief = models.OneToOneField(person, on_delete=models.CASCADE,primary_key=True)
    phone_number = models.CharField('Telefono del jefe familiar', max_length=20)
    property = models.CharField('Titulo de la Vivienda', max_length=20,default='Propietario',choices=PROPIEDAD)
    home = models.ForeignKey(home, on_delete=models.CASCADE)

    class Meta:
        """Meta definition for jefe_familiar."""

        verbose_name = 'jefe_familiar'
        verbose_name_plural = 'jefes_familiares'

    def __str__(self):
        """Unicode representation of jefe_familiar."""
        return '{0} {1}  C.I.:{2}'.format(self.chief.name_person, self.chief.last_name_person, self.chief.dni)

class grupo_familiar(models.Model):
    """Model definition for grupo_familiar."""

    RELATION = [(None,'Selecione una opcion'),('Hijo/a','Hijo/a'), ('Sobrino/a','Sobrino/a'), ('Hermano/a','Hermano/a'), ('Primo/a','Primo/a'),('Nieto/a','Nieto/a')]


    familiar = models.OneToOneField(person, on_delete=models.CASCADE,primary_key=True)
    relationship = models.CharField('Parentesco', max_length=20,blank=False,null=False,choices=RELATION)
    chief = models.ForeignKey(jefe_familiar, on_delete=models.CASCADE)

    class Meta:
        """Meta definition for grupo_familiar."""

        verbose_name = 'grupo_familiar'
        verbose_name_plural = 'grupo_familiares'

    def __str__(self):
        """Unicode representation of jefe_familiar."""
        return '{0} {1}  ({2})'.format(self.familiar.name_person, self.familiar.last_name_person,self.relationship)


class datos_cuidado(models.Model):
    """Model definition for datos_cuidado."""

    familiar = models.OneToOneField(grupo_familiar, on_delete=models.CASCADE)
    breastmilk = models.CharField('El niño consume leche materna', max_length=10,blank=False,null=False)
    breastmilk_intake = models.IntegerField('Veces que consime leche materna al dia')
    bottle = models.CharField('Consumo de tetero del niño', max_length=10, blank=False,null=False)
    solid_food = models.CharField('Consumo de alimentos solidos del niño', max_length=10,blank=False,null=False)
    boiled_water = models.CharField('Agua para el consumo es hervida', max_length=10,blank=False,null=False)
    filtred_water = models.CharField('Agua para el consumo es filtrada', max_length=10,blank=False,null=False)
    purified_water = models.CharField('Agua para el consumo es filtrada', max_length=10,blank=False,null=False)
    flu_cough = models.CharField('Manifesto Gripe o tos la ultima semana', max_length=10,blank=False,null=False)
    fever = models.CharField('Manifesto fiebre la ultima semana', max_length=10,blank=False,null=False)
    diarrhea = models.CharField('Manifesto diarrea la ultima semana', max_length=10,blank=False,null=False)
    vomit = models.CharField('Presento vomito la ultima semana', max_length=10,blank=False,null=False)
    dehydrataded = models.CharField('Presento deshidratacion la ultima semana', max_length=10,blank=False,null=False)
    malaria = models.CharField('Presento paludismo la ultima semana', max_length=10, blank=False,null=False)

    class Meta:
        """Meta definition for datos_cuidado."""

        verbose_name = 'datos_cuidado'
        verbose_name_plural = 'datos_cuidados'

    def __str__(self):
        """Unicode representation of datos_cuidado."""
        return self.familiar

class nursery(models.Model):
    """Model definition for nursery."""

    nursery = models.AutoField(primary_key=True)
    name_nursery = models.CharField('Nombre del vivero',max_length=50,default='Vivero')
    start_date = models.DateField('Fecha de inicio del vivero', auto_now=False, auto_now_add=False)
    end_date = models.DateField('Fecha final del vivero', auto_now=False, auto_now_add=False)
    status = models.BooleanField('Estado del Viviero',default=True)
    church_group = models.ForeignKey(church_group, on_delete=models.CASCADE)

    class Meta:
        """Meta definition for vivero."""

        verbose_name = 'vivero'
        verbose_name_plural = 'viveros'

    def __str__(self):
        """Unicode representation of vivero."""
        return self.name_nursery

class datos_pesaje(models.Model):
    """Model definition for datos_pesaje."""

    data_weighing = models.AutoField(primary_key=True)
    height = models.FloatField('Altura del niño',blank=False,null=False)
    weight = models.FloatField('Peso del niño',blank=False,null=False)
    c_arm = models.FloatField('Circuferencia del brazo del niño',blank=False,null=False)
    z_score = models.IntegerField('Indice de desnutricion del niño')
    accepted = models.BooleanField(default=True)
    delivery = models.IntegerField(default=3)
    nursery = models.ForeignKey(nursery, on_delete=models.CASCADE)
    familiar = models.ForeignKey(grupo_familiar, on_delete=models.CASCADE,max_length=30)

    class Meta:
        """Meta definition for datos_pesaje."""

        verbose_name = 'datos_pesaje'
        verbose_name_plural = 'datos_pesajes'

    def __str__(self):
        """Unicode representation of datos_pesaje."""
        return self.familiar.familiar.name_person

class datos_pesaje_embarazada(models.Model):
    """Model definition for datos_pesaje."""

    data_weighing = models.AutoField(primary_key=True)
    height = models.FloatField('Altura de la Embarazada',blank=False,null=False)
    weight = models.FloatField('Peso de la Embarazada',blank=False,null=False)
    c_arm = models.FloatField('Circuferencia del brazo de la Embarazada',blank=False,null=False)
    z_score = models.IntegerField('Indice de desnutricion de la Embarazada')
    gestation = models.IntegerField('Semana de Gestacion')
    accepted = models.BooleanField(default=True)
    nursery = models.ForeignKey(nursery, on_delete=models.CASCADE)
    familiar = models.ForeignKey(jefe_familiar, on_delete=models.CASCADE,max_length=30)

    class Meta:
        """Meta definition for datos_pesaje."""

        verbose_name = 'datos_pesaje'
        verbose_name_plural = 'datos_pesajes'

    def __str__(self):
        """Unicode representation of datos_pesaje."""
        return self.familiar

class priest(models.Model):
    """Model definition for parroco."""

    priest = models.CharField(primary_key=True,max_length=10)
    status = models.BooleanField('Estado del parroco en la iglesia', default=True)
    start_date = models.DateField('Fecha de inicio del parroco en la igleisa',auto_now_add=True)
    person = models.ForeignKey(person, on_delete=models.CASCADE)
    church = models.ForeignKey(church, on_delete=models.CASCADE)

    class Meta:
        """Meta definition for parroco."""

        verbose_name = 'parroco'
        verbose_name_plural = 'parrocos'

    def __str__(self):
        """Unicode representation of parroco."""
        return '{0},{1}'.format(self.persona.nombre_persona, self.persona.apellido_persona)

class integrant_church_group(models.Model):
    """Model definition for integrante_grupo_parroquial."""

    integrant = models.AutoField(primary_key=True)
    status = models.BooleanField('Estado del integrante en el grupo', default=True)
    start_date = models.DateField('Fecha de inicio', auto_now_add=False)
    rank = models.CharField('Cargo del integrando dentro del grupo', max_length=20, blank=True, null=True)
    person = models.ForeignKey(person, on_delete=models.CASCADE)
    church_group = models.ForeignKey(church_group, on_delete=models.CASCADE)

    class Meta:
        """Meta definition for integrante_grupo_parroquial."""

        verbose_name = 'integrante_grupo_parroquial'
        verbose_name_plural = 'integrante_grupo_parroquiales'

    def __str__(self):
        """Unicode representation of integrante_grupo_parroquial."""
        return '{0} {1}'.format(self.person.name_person, self.person.last_name_person)

templates/childs/care_dates.html
{% extends 'homes/list_home.html' %}
{% load static %}

{% block title %}Datos del Cuidado del niño{% endblock title %}

{% block page_title %}Datos del Cuidado del niño{% endblock page_title %}

{% block form_ubicacion %}
{% endblock form_ubicacion %}

    {% block content %}
    <div class="container bg-white rounded mb-4 pb-3">
        <h1 class="fs-3 mt-3 mx-5">Datos del Representante</h1>
        <div class="row border-bottom rounded-bottom">
            <div class="col-5 mb-3 input-group">
                {{ form_home.chief }}
                <button class="btn btn-success input-group-text" type="button" id="search" onclick="buscar(`{% url 'childs:list_chief' %}`);">
                    <i class="fas fa-search fa-2x "></i>
                  </button>
            </div>
    <h1 class="fs-4 mt-3 mx-5">Datos del Niño</h1>
    <form action="" method="post">{% csrf_token %}
        <div class="row justify-content-around">
            <div class="col-5 my-3">
                <div>
                    <label class="my-3">Niño</label>
                    {{ care_dates.familiar }}
                </div>
                <label for="leche_materna" class="form-label my-3">¿Consume Leche Materna?</label>
                {{ care_dates.breastmilk }}
                <label for="tetero" class="form- my-3">¿Usa Tetero?</label>
                {{ care_dates.bottle }}
            </div>
            <div class="col-5 my-3">
                <label for="consumo_leche" class="form-label my-3">Consumo de leche materna al dia</label>
                {{ care_dates.breastmilk_intake }}
                <label class="form-label my-3">Otros Alimentos Solidos</label>
                {{ care_dates.solid_food }}
            </div>
        <div class="row justify-content-around">
            <h1 class="fs-5">El agua para el consumo es:</h1>
            <div class="col-4 my-3">
                <h1 class="fs-6">Hervida:</h1>
                {{ care_dates.boiled_water }}
            </div>
            <div class="col-4 my-3">
                <h1 class="fs-6">Purificada:</h1>
                {{ care_dates.purified_water }}
        </div>
        <div class="col-4 my-3">
            <h1 class="fs-6">Filtrada o Clorada:</h1>
            {{ care_dates.filtred_water }}
        </div>
        </div>
        <div class="row justify-content-around">
        <h1 class="fs-5">Enfermedad la ultima semana:</h1>
        <div class="col-4 my-3">
            <h1 class="fs-6">Gripe o Tos:</h1>
            {{ care_dates.flu_cough}}
        </div>
        <div class="col-4 my-3">
            <h1 class="fs-6">Firbre:</h1>
            {{ care_dates.fever}}
        </div>
        <div class="col-4 my-3">
            <h1 class="fs-6">Diarrea:</h1>
            {{ care_dates.diarrhea}}
        </div>
        </div>
        <div class="row justify-content-around">
        <div class="col-4 my-3">
            <h1 class="fs-6">Vomito:</h1>
            {{ care_dates.vomit}}
        </div>
        <div class="col-4 my-3">
            <h1 class="fs-6">Deshidratado:</h1>
            {{ care_dates.dehydrataded}}
        </div>
        <div class="col-4 my-3">
            <h1 class="fs-6">Paludismo:</h1>
            {{ care_dates.malaria}}
        </div>
        </div>
    <div class="row justify-content-end">
        <button type="submit" class="btn btn-primary m-1 col-1">Enviar</button>
    </div>
</form>
</div>

<div class="modal fade" id="list_person" role="dialog"></div>

{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/childs.js' %}"></script>
{% endblock scripts %}

templates/childs/create_chief.html
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Creacion de Jefe Familiar(Representante)</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form_creacion_chief" action="{% url 'childs:create_chief' %}" method="POST">
          {% csrf_token %}
            <div class="modal-body">
              <div id="errores">
              </div>              
              {{ form.chief.label }}
              <div class="invisible" id="no_search">
                <div class="position-absolute start-10">
                  <strong id="msg"></strong>
                  <button class="btn btn-primary " data-bs-target="#creacion_person" onclick="abrir_modal_creacion_person(`{% url 'childs:create_person' %}`);" >Agregar Persona</button>
                </div>
              </div>
              <div class="input-group col-5 border-bottom mb-3">
                {{ form.chief }}
                <button class="btn btn-success input-group-text" type="button" id="search" onclick="buscar(`{% url 'childs:list_person' %}`);">
                  <i class="fas fa-search fa-2x "></i>
                </button>
              </div>
              {{ form.phone_number.label }}
              {{ form.phone_number }}
              {{ form.property.label }}
              {{ form.property }}
              {{ form.home.label }}
              {{ form.home }}
            </div>
            <div class="modal-footer">
              <button class="btn btn-danger" type="button" data-bs-dismiss="modal">Cancelar</button>
              <button id="boton_creacion" class="btn btn-primary" type="button" onclick="registrar_chief();">Confirmar</button>
            </div>
        </form>
      </div>
    </div>
  </div>
    <script>
      home();
  </script>

templates/childs/create_chief_home.html
{% extends 'homes/list_home.html' %}
{% load static %}

{% block title %}Datos del Representante{% endblock title %}

{% block page_title %}Datos del Representante{% endblock page_title %}

{% block form_ubicacion %}
<div class="container bg-white rounded mb-4 pb-3">
    <div class="invisible" id="alert">
        <div class="alert alert-success position-absolute col-6 justify-content-between d-flex" role="alert">
            <i class="fas fa-check-circle fa-2x alert-link"></i>
            <p id="msg_alert"></p>
            <button type="button" class="btn btn-success col-1 " data-bs-dismiss="alert" aria-label="Close">Ok</button>
        </div>
    </div>
    <div class="row border-bottom justify-content-around">
        <h1 class="fs-3 mt-3 mx-5">Ubicación</h1>
        <div class="row mb-3">
            <div class="col-5 my-3">
                <label for="parroquia">Parroquia</label>
                {{ form_ubication.parish }}
            </div>
            <div class="col-5 my-3">
                <label for="comunidad">Comunidad</label>
                {{ form_ubication.community }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-5 my-3">
                {{ form_ubication.sector.label }}
                {{ form_ubication.sector }}
            </div>
        </div>

        {% block barra_busqueda %}
        {% endblock barra_busqueda %}
    </div>
    {% endblock form_ubicacion %}

    {% block content %}
    <h1 class="fs-3 mt-3 mx-5">Datos del Representante</h1>
    <div class="row border-bottom rounded-bottom">
        <div class="col-5 mb-3">
            <label for="home">Vivienda</label>
            {{ form_home.home }}
        </div>
        <div class="col-5">
            <label for="vivienda">Representante</label>
            <div class="mb-3 input-group">
                {{ form_home.chief }}
                <button class="btn btn-primary input-group-text" id="menu-btn" type="button" onclick="abrir_modal_creacion_chief(`{% url 'childs:create_chief' %}`);">
                    <span class="btn-label">
                        <i class="fas fa-search fa-2x "></i>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-end">
        <div class="col-2">
            <a href="{% url 'childs:initial_diagnostic' %}">
                <button class="btn btn-primary btn-lg">Siguiente</button>
            </a>
        </div>
    </div>

<div class="modal fade" id="creacion_chief" role="dialog"></div>

<div class="modal fade" id="list_person" role="dialog"></div>
    
<div class="modal fade" id="creacion_person" role="dialog"></div>

{% endblock content %}




{% block scripts %}
    <script src="{% static 'js/childs.js' %}"></script>
{% endblock scripts %}

templates/childs/create_familiar.html
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Creacion de Grupo Familiar(Niño)</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form_creacion_familiar" action="{% url 'childs:create_familiar' %}" method="POST">
            {% csrf_token %}
            <div class="modal-body">
                <div id="errores">
                </div>
                {{ form.familiar.label }}
                {{ form.familiar }}
                {{ form.chief.label }}
                {{ form.chief }}
                {{ form.relationship.label }}
                {{ form.relationship }}
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" data-bs-dismiss="modal">Cancelar</button>
                <button id="boton_creacion" class="btn btn-primary" type="button" onclick="registrar_familiar();">Confirmar</button>
            </div>
        </form>
      </div>
    </div>
  </div>
  <script>
    chief();
  </script>

templates/childs/create_person.html
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Creacion de Persona</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form_creacion_person" action="{% url 'childs:create_person' %}" method="POST">
            {% csrf_token %}
            <div class="modal-body">
                <div id="errores">
                </div>
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" data-bs-dismiss="modal">Cancelar</button>
                <button id="boton_creacion" class="btn btn-primary" type="button" onclick="registrar_person();" >Confirmar</button>
            </div>
        </form>
      </div>
    </div>
  </div>

templates/childs/create_person_familiar.html
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Creacion de Persona</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form_creacion_person" action="{% url 'childs:create_person' %}" method="POST">
            {% csrf_token %}
            <div class="modal-body">
                <div id="errores">
                </div>
                {{ form.dni }}
                {{ form.name_person.label }}
                {{ form.name_person }}
                {{ form.last_name_person.label }}
                {{ form.last_name_person }}
                {{ form.gener.label }}
                {{ form.gener }}
                {{ form.birth_date.label }}
                {{ form.birth_date }}
                {{ form.category }}
                
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" data-bs-dismiss="modal">Cancelar</button>
                <button id="boton_creacion" class="btn btn-primary" type="button" onclick="registrar_person_child();" >Confirmar</button>
            </div>
        </form>
      </div>
    </div>
  </div>

templates/childs/edit_child.html
{% extends 'childs/initial_diagnostic.html' %}

{% block title %}Editar Datos{% endblock title %}

{% block page_title %}Editar Datos{% endblock page_title %}

templates/childs/initial_diagnostic.html
{% extends 'navbar.html' %}
{% load static %}

{% block title %}Datos Basicos del Niño{% endblock title %}

{% block page_title %}Datos Basicos del Niño{% endblock page_title %}

{% block content %}
<div class="container bg-white rounded mb-4 pb-3">
    <h1 class="fs-3 mt-3 mx-5">Datos del Representante</h1>
    <div class="row border-bottom rounded-bottom">
        </div>
        <label for="vivienda">Representante</label>
            <div class="col-5 mb-3 input-group">
                {{ form_home.chief }}
                <button class="btn btn-success input-group-text" type="button" id="search" onclick="buscar(`{% url 'childs:list_person' %}`);">
                    <i class="fas fa-search fa-2x "></i>
                  </button>
            </div>
    <h1 class="fs-4 mt-3 mx-5">Datos del Niño</h1>
    <form action="" method="post">{% csrf_token %}
        <div class="row">
            <label class="mt-3">Niño</label>
            <div class="col-6">
                <div class="input-group">
                    {{ weighing_form.familiar }}
                    <button class="btn btn-primary input-group-text" id="menu-btn" type="button" onclick="abrir_modal_creacion_person(`{% url 'childs:create_person_familiar' %}`);">
                        <i class="fas fa-search fa-2x "></i>
                    </button>
                </div>
                <div class="form-floating my-3">
                    {{ weighing_form.height }}
                    <label for="id_height" class="form-label">Talla</label>
                </div>
                <div class="form-floating my-3">
                    {{ weighing_form.c_arm }}
                    <label for="id_c_arm" class="form-label">Circunferencia del brazo</label>
                </div>
                <div class="invisible">
                    {{ weighing_form.accepted }}
                </div>
            </div>
            <div class="col-5">
                <label class="">Vivero</label>
                    {{ weighing_form.nursery }}
                    <div class="form-floating my-3">
                    <div class="form-floating my-3">
                        {{ weighing_form.weight }}
                        <label for="id_weight" class="form-label">Peso</label>
                    </div>
                </div>
                <div class="form-floating my-3">
                    {{ weighing_form.z_score }}
                    <label for="id_z_score" class="form-label">Z Score</label>
                </div>
            </div>
        </div>
        <div class="row justify-content-around">
            <button type="submit" class="btn btn-primary m-1 col-1">Enviar</button>
    </div>
</form>
</div>


<div class="modal fade" id="creacion_person" role="dialog"></div>

<div class="modal fade" id="list_person" role="dialog"></div>

<div class="modal fade" id="creacion_familiar" role="dialog"></div>

{% endblock content %}



{% block scripts %}
<script src="{% static 'js/childs.js' %}"></script>
{% endblock scripts %}

templates/childs/initial_diagnostic_embarazada.html
{% extends 'navbar.html' %}
{% load static %}

{% block title %}Datos de la Embarazada{% endblock title %}

{% block page_title %}Datos de la Embarazada{% endblock page_title %}

{% block form_ubicacion %}
<div class="container bg-white rounded mb-4 pb-3">
    <div class="invisible" id="alert">
        <div class="alert alert-success position-absolute col-6 justify-content-between d-flex" role="alert">
            <i class="fas fa-check-circle fa-2x alert-link"></i>
            <p id="msg_alert"></p>
            <button type="button" class="btn btn-success col-1 " data-bs-dismiss="alert" aria-label="Close">Ok</button>
        </div>
    </div>
    <div class="row border-bottom justify-content-around">
        <h1 class="fs-3 mt-3 mx-5">Ubicación</h1>
        <div class="row mb-3">
            <div class="col-5 my-3">
                <label for="parroquia">Parroquia</label>
                {{ form_ubication.parish }}
            </div>
            <div class="col-5 my-3">
                <label for="comunidad">Comunidad</label>
                {{ form_ubication.community }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-5 my-3">
                {{ form_ubication.sector.label }}
                {{ form_ubication.sector }}
            </div>
        </div>

        {% block barra_busqueda %}
        {% endblock barra_busqueda %}
    </div>
    {% endblock form_ubicacion %}
{% block content %}
<div class="container bg-white rounded mb-4 pb-3">
    <h1 class="fs-4 mt-3 mx-5">Datos de la Embarazada</h1>
    <div class="row border-bottom rounded-bottom">
        <div class="col-5 mb-3">
            <label for="home">Vivienda</label>
            {{ form_home.home }}
        </div>
        <div class="col-5 mb-3">
            <form action="" method="post">{% csrf_token %}
            <label for="vivienda">Embarazada</label>
            {{ weighing_form.familiar }}
            <button class="px-2 py-1 btn btn-primary mt-4" id="menu-btn" type="button" onclick="abrir_modal_creacion_chief(`{% url 'childs:create_chief' %}`);">
                <span class="btn-label">
                    Agregar Embarazada
                </span>
            </button>
        </div>
    </div>
        <div class="row">
            <div class="col-6 my-3">
                <div class="form-floating my-3">
                    {{ weighing_form.height }}
                    <label for="id_height" class="form-label">Talla</label>
                </div>
                <div class="form-floating my-3">
                    {{ weighing_form.c_arm }}
                    <label for="id_c_arm" class="form-label">Circunferencia del brazo</label>
                </div>
                <div class="form-floating my-3">
                    {{ weighing_form.gestation }}
                    <label for="id_gestation" class="form-label">Semana de Gestacion</label>
                </div>
            </div>
            <div class="col-5 my-3">
                <label class="mt-3">Vivero</label>
                {{ weighing_form.nursery }}
                <div class="form-floating my-3">
                    <div class="form-floating my-3">
                        {{ weighing_form.weight }}
                        <label for="id_weight" class="form-label">Peso</label>
                    </div>
                </div>
                <div class="form-floating my-3">
                    {{ weighing_form.z_score }}
                    <label for="id_z_score" class="form-label">Z Score</label>
                </div>
                <div class="invisible">
                    {{ weighing_form.accepted }}
                </div>
            </div>
        </div>
        <div class="row justify-content-around">
            <button type="submit" class="btn btn-primary m-1 col-1">Enviar</button>
    </div>
</form>
</div>


<div class="modal fade" id="creacion_person" role="dialog"></div>

<div class="modal fade" id="creacion_chief" role="dialog"></div>

{% endblock content %}



{% block scripts %}
<script src="{% static 'js/childs.js' %}"></script>
{% endblock scripts %}